import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import excel  from './excel'

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new ({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: excel.client_email,
  key: excel.private_key,
  scopes: [
    'https://www.googleapis.com/auth/spreadsheets',
  ],
});


const doc = new GoogleSpreadsheet('1zlwW4rA94xC41JG8IjNjFON473rb-UpI_9U9fWa6nBk', serviceAccountAuth);
const sheet = await doc.addSheet({ headerValues: ['name', 'email',"phone","college","department"] });

export const usepost =()=>{

    const sheets =async(document)=>{

        const larryRow = await sheet.addRow(document);
    }

    return {sheets}
}
